
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-disease-api
  template:
    metadata:
      labels:
        app: heart-disease-api
    spec:
      containers:
      - name: heart-disease-api
        image: heart-disease-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
